[SystrayQuit]
hash = "sha1-1a2285d8881f226e13430515a9dd2b9fb6294200"
other = "é€€å‡º"

[SystrayQuitTooltip]
hash = "sha1-9911e92e81350237d54e470c1e6122fa94a7d968"
other = "é€€å‡ºtgbot-upnp"

[TgBotAbout]
hash = "sha1-a1b8a24eb760a6bcb5dd2446909b5187310fca47"
other = "å°†telegramè§†é¢‘é€šè¿‡upnpåè®®æŠ•å±è‡³å…¶ä»–è®¾å¤‡ https://github.com/tgbot-upnp/tgbot-upnp"

[TgBotAuthFailed]
hash = "sha1-d747acd681fd72e61744de5d224013f5b667557b"
other = "æ‚¨çš„ç”¨æˆ·IDï¼š{{.userID}}\næ‚¨ä¸æ˜¯å½“å‰tgbot-upnpçš„ç®¡ç†å‘˜ï¼Œæ— æ³•ä½¿ç”¨æ­¤æœºå™¨äººã€‚æ‚¨å¯ä»¥è”ç³»ç®¡ç†å‘˜å°†æ‚¨çš„ç”¨æˆ·IDæ·»åŠ è‡³ç®¡ç†å‘˜åˆ—è¡¨ï¼Œæˆ–è€…éƒ¨ç½²è‡ªå·±çš„tgbot-upnpï¼Œè¯¦ç»†ä»‹ç»ï¼š https://github.com/tgbot-upnp/tgbot-upnp"

[TgBotCmdStart]
hash = "sha1-0dfc90ac94a89c00e250e95c760900140065d99b"
other = "æ¬¢è¿ä½¿ç”¨tgbot-upnp,æ‚¨å¯ä»¥å°†è§†é¢‘å‘é€åˆ°å½“å‰å¯¹è¯å¼€å§‹ä½ çš„æŠ•å±ä½“éªŒ"

[TgBotDescription]
hash = "sha1-b8c10945ca49d07ccf435d64b12e78b39eb0046b"
other = "tgbot-upnpæ˜¯ä¸€ä¸ªå¯ä»¥å°†telegramè§†é¢‘é€šè¿‡upnpåè®®æŠ•å±è‡³å…¶ä»–è®¾å¤‡çš„å°å·¥å…·ï¼Œæ‚¨å¯ä»¥å°†è§†é¢‘å‘é€åˆ°å½“å‰å¯¹è¯å¼€å§‹ä½ çš„æŠ•å±ä½“éªŒã€‚\nè¯¦ç»†ä»‹ç»ï¼šhttps://github.com/tgbot-upnp/tgbot-upnp"

[TgBotMsgDeviceUnavailable]
hash = "sha1-f4283b9c6fead2807ccfda9208b27c91064f5923"
other = "æ’­æ”¾è®¾å¤‡ä¸å¯ç”¨ï¼Œè¯·åˆ·æ–°åé‡è¯•"

[TgBotMsgPlay]
hash = "sha1-590e5535f923cf54a8daf27982395d9c7acdac88"
other = "â–¶ï¸ æ’­æ”¾"

[TgBotMsgRefresh]
hash = "sha1-9a108a00e612197bec6b2316abd9a1430c28baeb"
other = "ğŸ”„ åˆ·æ–°"

[TgBotMsgVideoPlayed]
hash = "sha1-06d51e56e0af676d91a82c7be51a29b76125e9ff"
other = "è§†é¢‘å·²å¼€å§‹æ’­æ”¾"